// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/belson77/Go-001/Week04/news/config/yaml"
	"github.com/belson77/Go-001/Week04/news/internal/comment-service/service"
	"github.com/belson77/Go-001/Week04/news/internal/pkg/database"
)

// Injectors from wire.go:

func initializeCommentService(f string) (*service.CommentService, error) {
	config, err := yaml.NewConfig(f)
	if err != nil {
		return nil, err
	}
	db, err := database.NewMysql(config)
	if err != nil {
		return nil, err
	}
	commentService := service.NewCommentService(db)
	return commentService, nil
}
